# Generated by Django 2.2.4 on 2019-10-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=19, null=True)),
                ('category', models.CharField(choices=[('', 'select'), ('BEAUTY', 'Beauty'), ('PERSONAL_CARE', 'Personal Care'), ('MEDICINE_AND_TREATMENT', 'Medicine & Treatment'), ('NATURAL_AND_ORGANIC', 'Natural & Organic'), ('SUPPLEMENT_AND_VITAMINS', 'Supplements & Vitamins')], default='select', max_length=20)),
                ('label', models.CharField(choices=[('', 'select'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='select', max_length=15)),
                ('description', models.TextField(max_length=3000)),
                ('additional_information', models.TextField(blank=True, max_length=3000)),
                ('slug', models.SlugField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField()),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.BillingAddress')),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
