# Generated by Django 2.2.4 on 2019-11-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
