# Generated by Django 2.2.4 on 2020-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='acitve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
