# Generated by Django 2.2.4 on 2019-09-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='About',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='items',
        ),
    ]
