# Generated by Django 2.2.4 on 2019-10-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAnAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=15)),
                ('tell_us_about_you', models.CharField(choices=[('', 'select'), ('Manufacturer', 'Manufacturer'), ('Wholesaler', 'Wholesaler')], default='select', max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('contact_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=70)),
                ('state', models.CharField(blank=True, max_length=70)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=19, null=True)),
                ('category', models.CharField(choices=[('', 'select'), ('BEAUTY', 'Beauty'), ('PERSONAL_CARE', 'Personal Care'), ('MEDICINE_AND_TREATMENT', 'Medicine & Treatment'), ('NATURAL_AND_ORGANIC', 'Natural & Organic'), ('SUPPLEMENT_AND_VITAMINS', 'Supplements & Vitamins')], default='select', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('detail', models.TextField(max_length=2500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
